# This is the DEV version of the all-in-one compose file.
# The overrides the build context so that it uses the local sources
# to build an image rather than the published image.

networks:
  pulumi-self-hosted-installers:
    # Setting external to true will prevent docker-compose from creating the
    # network if it doesn't exist already.
    external: true

  pulumi-services:

services:

  api:
    ports:
      - "8080:8080"
    image: "pulumi/service:edge@sha256:3b339cdf317de607aaf0a8683b59c02e9481a68379b78d70a8baab91ca2003cb"

  console:
    ports:
      - "3000:3000"
    image: "pulumi/console:edge@sha256:3f25fd2748821fd5eb4a87a9a1d42fbd7874eb7ad03015129d5084346e5df935"

  migration:
    image: "pulumi/migrations:edge@sha256:d3ec407582f1892cb8a3c29c16c6e85e2d8105a43806048436cd89cd06416bd0"
