on:
  push:
    # Sequence of patterns matched against refs/tags.
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0.

name: Create Release

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
    - name: Remove unnecessary files from for packaging
      run: |
        # Don't need tests and override files for the final package.
        rm -rf ./quickstart-docker-compose/tests
        rm -r **/*.override.yml

    - name: Upload artifact
      uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4
      with:
        # Artifact name
        name: pulumi-self-hosted-installers
        # Directory containing files to upload
        path: .
        overwrite: true

    - name: Create Release
      id: create_release
      uses: actions/create-release@0cb9c9b65d5d1901c1f53e5e66eaf4afd303e70e # v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Create release asset zip file
      run: |
        zip -r pulumi-self-hosted-installers.zip README.md \
        ./quickstart-docker-compose/*.env ./quickstart-docker-compose/*.yml \
        ./quickstart-docker-compose/all-in-one ./quickstart-docker-compose/scripts

    - name: Upload Release Asset
      id: upload-release-asset
      uses: actions/upload-release-asset@e8f9f06c4b078e705bd2ea027f0926603fc9b4d5 # v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        # This pulls from the CREATE RELEASE step above, referencing its ID to get its outputs object, which include a `upload_url`.
        # See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./pulumi-self-hosted-installers.zip
        asset_name: pulumi-self-hosted-installers.zip
        asset_content_type: application/zip
