name: AWS ECS TypeScript Tests

on:
  pull_request:
    paths:
      - 'ecs-hosted/ts/**'
      - 'tests/*ecs*ts*'
      - 'tests/*ecs*'
      - 'tests/utils.go'
      - 'tests/service_validation*'
    types: [opened, synchronize, labeled]
  workflow_dispatch:
    inputs:
      skip_validation:
        description: 'Skip service validation (true/false)'
        required: false
        default: 'false'

env:
  GO_VERSION: '1.23'
  NODE_VERSION: '20'

jobs:
  test-aws-ecs-ts:
    runs-on: ubuntu-latest
    timeout-minutes: 90
    environment: nightly-tests
    if: contains(github.event.pull_request.labels.*.name, 'test:aws-ecs-ts')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Install Pulumi CLI
        uses: pulumi/actions@v4

      - name: Run AWS ECS TypeScript tests
        run: make test-aws-ecs-ts
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: aws-ecs-ts-test-results
          path: tests/test-results/