name: GKE Tests

on:
  pull_request:
    paths:
      - 'gke-hosted/**'
      - 'tests/*gke*'
      - 'tests/utils.go'
      - 'tests/service_validation*'
    types: [opened, synchronize, labeled]
  workflow_dispatch:
    inputs:
      skip_validation:
        description: 'Skip service validation (true/false)'
        required: false
        default: 'false'

env:
  GO_VERSION: '1.23'
  NODE_VERSION: '20'

jobs:
  test-gke:
    runs-on: ubuntu-latest
    timeout-minutes: 90
    environment: nightly-tests
    if: contains(github.event.pull_request.labels.*.name, 'test:gke')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Install Pulumi CLI
        uses: pulumi/actions@v4

      - name: Run GKE tests
        run: make test-gke
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: gke-test-results
          path: tests/test-results/